const fs = require('fs');
let content = fs.readFileSync('src/app/buku/[slug]/page.jsx', 'utf8');

const oldStructure = `</div><div className="mt-7 border-y border-stone-200 py-6"><p className="font-bold">Deskripsi</p><p className="mt-3 leading-7 text-stone-600 whitespace-pre-wrap">{book.description || book.short_description || "Buku pilihan yang dikurasi Bukupagi untuk menemani rasa ingin tahu dan waktu membaca Anda."}</p></div></article><aside className="h-fit rounded-2xl border border-stone-200 bg-white p-5 shadow-sm lg:sticky lg:top-24"><h2 className="font-black">Atur jumlah & beli</h2><div className="mt-5 flex items-center justify-between"><span className="text-sm text-stone-600">Jumlah</span><div className="flex overflow-hidden rounded-lg border"><button onClick={() => setQuantity((n) => Math.max(1,n-1))} className="h-9 w-9">−</button><span className="grid w-9 place-items-center border-x text-sm font-bold">{quantity}</span><button onClick={() => setQuantity((n) => Math.min(book.stock || 10,n+1))} className="h-9 w-9">+</button></div></div><p className="mt-2 text-right text-xs text-stone-500">Stok tersisa: {book.stock}</p><button onClick={() => add(false)} disabled={book.stock <= 0} className="mt-6 w-full rounded-xl border border-blue-700 py-3 text-sm font-bold text-blue-700 disabled:opacity-50">+ Masukkan Keranjang</button><button onClick={() => add(true)} disabled={book.stock <= 0} className="mt-3 w-full rounded-xl bg-blue-700 py-3 text-sm font-bold text-white disabled:opacity-50">Beli Sekarang</button>{notice && <p className="mt-3 text-center text-xs font-bold text-blue-700">{notice}</p>}</aside></section><section className="mt-12 border-t border-stone-200 py-10"><h2 className="text-xl font-black">Detail Buku</h2><dl className="mt-5 grid max-w-3xl gap-5 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">Penerbit</dt><dd className="mt-1 font-bold">{book.publisher || "-"}</dd></div><div><dt className="text-stone-500">Tahun Terbit</dt><dd className="mt-1 font-bold">{book.publication_year || "-"}</dd></div><div><dt className="text-stone-500">Halaman</dt><dd className="mt-1 font-bold">{book.pages || "-"}</dd></div><div><dt className="text-stone-500">ISBN</dt><dd className="mt-1 font-bold">{book.isbn || "-"}</dd></div><div><dt className="text-stone-500">Berat</dt><dd className="mt-1 font-bold">{book.weight ? \`\${book.weight} gram\` : "-"}</dd></div><div><dt className="text-stone-500">SKU</dt><dd className="mt-1 font-bold">{book.sku || "-"}</dd></div></dl></section></div></main>;`;

const newStructure = `</div><div className="mt-7 border-t border-stone-200 pt-6"><p className="font-bold">Deskripsi</p><p className="mt-3 leading-7 text-stone-600 whitespace-pre-wrap">{book.description || book.short_description || "Buku pilihan yang dikurasi Bukupagi untuk menemani rasa ingin tahu dan waktu membaca Anda."}</p></div><div className="mt-7 border-t border-stone-200 pt-6 pb-6"><h2 className="font-bold">Detail Buku</h2><dl className="mt-4 grid gap-4 text-sm sm:grid-cols-2"><div><dt className="text-stone-500">Penerbit</dt><dd className="mt-1 font-bold">{book.publisher || "-"}</dd></div><div><dt className="text-stone-500">Tahun Terbit</dt><dd className="mt-1 font-bold">{book.publication_year || "-"}</dd></div><div><dt className="text-stone-500">Halaman</dt><dd className="mt-1 font-bold">{book.pages || "-"}</dd></div><div><dt className="text-stone-500">ISBN</dt><dd className="mt-1 font-bold">{book.isbn || "-"}</dd></div><div><dt className="text-stone-500">Berat</dt><dd className="mt-1 font-bold">{book.weight ? \`\${book.weight} gram\` : "-"}</dd></div><div><dt className="text-stone-500">SKU</dt><dd className="mt-1 font-bold">{book.sku || "-"}</dd></div></dl></div></article><aside className="h-fit rounded-2xl border border-stone-200 bg-white p-5 shadow-sm lg:sticky lg:top-24"><h2 className="font-black">Atur jumlah & beli</h2><div className="mt-5 flex items-center justify-between"><span className="text-sm text-stone-600">Jumlah</span><div className="flex overflow-hidden rounded-lg border"><button onClick={() => setQuantity((n) => Math.max(1,n-1))} className="h-9 w-9">−</button><span className="grid w-9 place-items-center border-x text-sm font-bold">{quantity}</span><button onClick={() => setQuantity((n) => Math.min(book.stock || 10,n+1))} className="h-9 w-9">+</button></div></div><p className="mt-2 text-right text-xs text-stone-500">Stok tersisa: {book.stock}</p><button onClick={() => add(false)} disabled={book.stock <= 0} className="mt-6 w-full rounded-xl border border-blue-700 py-3 text-sm font-bold text-blue-700 disabled:opacity-50">+ Masukkan Keranjang</button><button onClick={() => add(true)} disabled={book.stock <= 0} className="mt-3 w-full rounded-xl bg-blue-700 py-3 text-sm font-bold text-white disabled:opacity-50">Beli Sekarang</button>{notice && <p className="mt-3 text-center text-xs font-bold text-blue-700">{notice}</p>}</aside></section></div></main>;`;

content = content.replace(oldStructure, newStructure);

fs.writeFileSync('src/app/buku/[slug]/page.jsx', content);
