"use client";
/* eslint-disable @next/next/no-html-link-for-pages */
import { useEffect, useState } from "react";
import Link from "next/link";
import { api } from "../../../lib/api";
const Footer=({appName})=> <footer className="mt-auto border-t border-blue-100 bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-6 text-sm text-slate-500"><span>© 2026 {appName}.</span><span>Bantuan · Pengiriman</span></div></footer>;
const Sidebar=()=> <aside className="h-[280px] self-start rounded-3xl bg-gradient-to-b from-blue-950 to-blue-800 p-4 text-white shadow-xl"><p className="px-3 pb-3 text-[11px] font-bold uppercase tracking-[.18em] text-blue-300">Menu akun</p><nav className="space-y-1"><Link href="/akun" className="block rounded-xl px-3 py-3 text-sm text-blue-100">▦ Dashboard</Link><Link href="/akun/profil" className="block rounded-xl px-3 py-3 text-sm text-blue-100">👤 Profil</Link><Link href="/akun/pesanan" className="block rounded-xl px-3 py-3 text-sm text-blue-100">▣ Pesanan saya</Link><Link href="/" className="block rounded-xl px-3 py-3 text-sm text-blue-100">⌂ Kembali berbelanja</Link></nav></aside>;
export default function AddressPage(){const [addresses,setAddresses]=useState(null);const [settings, setSettings] = useState({});
  useEffect(() => { try { const c = JSON.parse(localStorage.getItem("app_settings") || "{}"); setSettings(prev => ({ ...prev, ...c })); } catch {} }, []);
  const appName = settings.app_name || "";
  const appLogo = settings.app_logo;
  useEffect(()=>{const token=localStorage.getItem("token");if(!token){window.location.href="/auth/login";return;}api("/settings").then(r => ((d) => { localStorage.setItem("app_settings", JSON.stringify(typeof d === "function" ? d(settings) : d)); setSettings(d); })(r.data||{})).catch(()=>null);
    api("/account",{headers:{Authorization:`Bearer ${token}`}}).then(r=>setAddresses(r.data.addresses||[])).catch(()=>setAddresses([]));},[]);return <main className="flex min-h-screen flex-col bg-[#f4f8ff] text-slate-800"><header className="border-b border-blue-100 bg-white"><div className="mx-auto flex max-w-7xl justify-between px-5 py-4"><Link href="/" className="flex items-center gap-2 font-black text-blue-950">{appLogo ? <img src={appLogo} alt={appName} className="h-8 w-8 rounded-lg object-contain" /> : <span className="grid h-8 w-8 place-items-center rounded-xl bg-blue-700 text-white">{(appName || " ")[0].toUpperCase()}</span>} {appName}</Link><Link href="/akun" className="text-sm font-bold text-blue-700">← Dashboard</Link></div></header><div className="mx-auto grid w-full max-w-7xl flex-1 gap-6 px-5 py-7 lg:grid-cols-[235px_1fr]"><Sidebar/><section><p className="text-sm font-semibold text-blue-700">Akun pelanggan</p><h1 className="mt-1 text-3xl font-black">Alamat Pengiriman</h1><div className="mt-6 grid gap-4 md:grid-cols-2">{!addresses?<p>Memuat alamat…</p>:addresses.length?addresses.map(a=><article key={a.id} className="rounded-2xl bg-white p-6 shadow-sm"><b>{a.recipient_name}</b><p className="mt-1 text-sm text-slate-600">{a.phone}</p><p className="mt-3 text-sm leading-6 text-slate-600">{a.address_line_1}, {a.city}, {a.province} {a.postal_code}</p></article>):<div className="rounded-2xl bg-white p-10 text-center"><b>Belum ada alamat</b><p className="mt-2 text-sm text-slate-500">Alamat dapat ditambahkan saat checkout.</p></div>}</div></section></div><Footer appName={appName}/></main>;}
